version: "3"

services:
  database:
    image: postgres:14.3-alpine
    container_name: database
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - network
    restart: unless-stopped
    env_file:
      - "./.env"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    env_file:
      - "./.env"
    ports:
      - 3000:3000
    networks:
      - network
    volumes:
      - ./backend:/usr/src/backend
    command: npm run start:dev
    depends_on:
      - database

networks:
  network:
    driver: bridge
