version: "3"

services:
  database:
    image: postgres:14.3-alpine
    container_name: database
    volumes:
      - ./database:/data/postgres
    ports:
      - 5433:5432
    networks:
      - network
    restart: unless-stopped
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - network
    volumes:
      - ./backend:/usr/src/backend

networks:
  network:
    driver: bridge
