version: "3"

services:
  database:
    image: postgres:14.3-alpine
    container_name: database
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped
    env_file:
      - "./.env"
