name: Production deploy
on:
  push:
    branches:
      - "main"

jobs:
  clean-repo:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

  deploy-bot:
    runs-on: self-hosted
    steps:
      - name: Stop running services
        run: docker compose -f docker-compose.production.yml --env-file .env down
      - name: Pull latest services
        run: docker compose -f docker-compose.production.yml pull
      - name: Build services
        run: docker compose -f docker-compose.production.yml --env-file .env build
      - name: Run services
        run: docker compose -f docker-compose.production.yml --env-file .env up -d
      - name: Status
        run: docker ps -a
